# Generated by Django 5.2.5 on 2025-08-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_lesson_owner_rate_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Время последнего обновления"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rate",
            name="description",
            field=models.CharField(blank=True, null=True),
        ),
    ]
