# Generated by Django 5.2.5 on 2025-08-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rate",
            options={"verbose_name": "course", "verbose_name_plural": "courses"},
        ),
    ]
