# Generated by Django 5.2.5 on 2025-08-20 14:09

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_payments_amount_alter_user_city_subscription"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user.models.UserManager()),
            ],
        ),
    ]
