# Generated by Django 5.2.5 on 2025-08-20 17:53

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="payments",
            name="amount",
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(default="Unknown"),
        ),
    ]
